# Data Handling with Pandas


In next examples we'll be using a simple moc dataset [developers.csv](https://github.com/ProgressBG-Python-Course/ProgressBG-Python-Slides/blob/gh-pages/pages/themes/dataScienceBasics/datasets/developers.csv)

In [1]:
import pandas as pd

## Load the data

Note that pandas has many functions for I/O from various file formats: [Pandas IO tools](https://pandas.pydata.org/docs/user_guide/io.html)
### From CSV

In [2]:
csv_file = "https://raw.githubusercontent.com/ProgressBG-Python-Course/ProgressBG-Python-Slides/refs/heads/gh-pages/pages/themes/dataScienceBasics/datasets/developers.csv"

# Read the CSV data into a Pandas DataFrame
df = pd.read_csv(csv_file)
df

  Developer  Age  Salary
0     Alice   30   60000
1     Boris   25   55000
2   Charlie   35   70000
3   Dimitar   28   62000
4       Eve   32   65000
5    Georgi   27   58000
6     Grace   40   80000
7    Hristo   29   61000
8      Ivan   31   63000
9   Kaloyan   26   57000

### From Excel (.xlsx)

In [3]:
xlsx_file = "https://github.com/ProgressBG-Python-Course/ProgressBG-Python-Slides/raw/refs/heads/gh-pages/pages/themes/dataScienceBasics/datasets/developers.xlsx"

# Read the CSV data into a Pandas DataFrame
df = pd.read_excel(xlsx_file)
df

  Developer  Age  Salary
0     Alice   30   60000
1     Boris   25   55000
2   Charlie   35   70000
3   Dimitar   28   62000
4       Eve   32   65000
5    Georgi   27   58000
6     Grace   40   80000
7    Hristo   29   61000
8      Ivan   31   63000
9   Kaloyan   26   57000

### From HTML

In [ ]:
tables = pd.read_html('https://pandas.pydata.org/docs/user_guide/io.html')
print(f"Found {len(tables)} tables!")
df_pandas_io = tables[0]
df_pandas_io

Found 9 tables!

,Format Type,Data Description,Reader,Writer
0,text,CSV,read_csv,to_csv
1,text,Fixed-Width Text File,read_fwf,NaN
2,text,JSON,read_json,to_json
3,text,HTML,read_html,to_html
4,text,LaTeX,Styler.to_latex,NaN
5,text,XML,read_xml,to_xml
6,text,Local clipboard,read_clipboard,to_clipboard
7,binary,MS Excel,read_excel,to_excel
8,binary,OpenDocument,read_excel,NaN
9,binary,HDF5 Format,read_hdf,to_hdf
10,binary,Feather Format,read_feather,to_feather
11,binary,Parquet Format,read_parquet,to_parquet
12,binary,ORC Format,read_orc,to_orc
13,binary,Stata,read_stata,to_stata
14,binary,SAS,read_sas,NaN
15,binary,SPSS,read_spss,NaN
16,binary,Python Pickle Format,read_pickle,to_pickle
17,SQL,SQL,read_sql,to_sql
18,SQL,Google BigQuery;:ref:read_gbq<io.bigquery>;:re...,NaN,NaN

## Getting a First Look at the Data

In [5]:
# Get data size
df.shape

(10, 3)

In [6]:
# Show first 5 rows
df.head()

  Developer  Age  Salary
0     Alice   30   60000
1     Boris   25   55000
2   Charlie   35   70000
3   Dimitar   28   62000
4       Eve   32   65000

In [7]:
# Show last 5 rows
df.tail()

  Developer  Age  Salary
5    Georgi   27   58000
6     Grace   40   80000
7    Hristo   29   61000
8      Ivan   31   63000
9   Kaloyan   26   57000

In [8]:
# Information about the DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Developer  10 non-null     object
 1   Age        10 non-null     int64
 2   Salary     10 non-null     int64
dtypes: int64(2), object(1)
memory usage: 372.0+ bytes

In [9]:
# Descriptive statistics
df.describe()

             Age        Salary
count  10.000000     10.000000
mean   30.300000  63100.000000
std     4.522782   7309.810759
min    25.000000  55000.000000
25%    27.250000  58500.000000
50%    29.500000  61500.000000
75%    31.750000  64500.000000
max    40.000000  80000.000000

## Selecting Columns and Rows

In [10]:
# Select a single column
df['Age']

0    30
1    25
2    35
3    28
4    32
5    27
6    40
7    29
8    31
9    26
Name: Age, dtype: int64

In [11]:
# Select multiple columns
df[['Age', 'Salary']]

   Age  Salary
0   30   60000
1   25   55000
2   35   70000
3   28   62000
4   32   65000
5   27   58000
6   40   80000
7   29   61000
8   31   63000
9   26   57000

In [12]:
# Select rows by index
print(df.iloc[0]) # First row
print()
print(df.iloc[0:5]) # First 5 rows

Developer    Alice
Age             30
Salary       60000
Name: 0, dtype: object

  Developer  Age  Salary
0     Alice   30   60000
1     Boris   25   55000
2   Charlie   35   70000
3   Dimitar   28   62000
4       Eve   32   65000

## Sorting and Filtering Data

In [13]:
df.sort_values(by='Salary', ascending=False)

  Developer  Age  Salary
6     Grace   40   80000
2   Charlie   35   70000
4       Eve   32   65000
8      Ivan   31   63000
3   Dimitar   28   62000
7    Hristo   29   61000
0     Alice   30   60000
5    Georgi   27   58000
9   Kaloyan   26   57000
1     Boris   25   55000

In [14]:
# Select rows based on condition
df[df['Age'] >= 30]

  Developer  Age  Salary
0     Alice   30   60000
2   Charlie   35   70000
4       Eve   32   65000
6     Grace   40   80000
8      Ivan   31   63000

In [15]:
# Filter data based on multiple conditions
mean_salary = df['Salary'].mean()
df[(df['Age'] <= 35) & (df['Salary'] >= mean_salary)]

  Developer  Age  Salary
2   Charlie   35   70000
4       Eve   32   65000

## Save and export data 

### To CSV

In [16]:
# 1. Basic CSV export
df.to_csv('developers_basic.csv', index=False)
print("Basic CSV export completed: developers_basic.csv")

# 2. CSV with custom separator and formatting
df.to_csv('developers_custom.csv',
          index=False,
          sep=';',                # Use semicolon as separator
          decimal=',',            # Use comma as decimal separator (European format)
          encoding='utf-8')       # Specify encoding
print("Custom CSV export completed: developers_custom.csv")

Basic CSV export completed: developers_basic.csv
Custom CSV export completed: developers_custom.csv

### To Excel (.xlsx)

Note, that the openpyxl module is needed when working with Excel (.xlsx) files in Pandas.
So, make sure that you have it: `pip install openpyxl`

In [17]:
# 1. Basic Excel export
df.to_excel('developers_basic.xlsx', index=False)
print("Basic Excel export completed: developers_basic.xlsx")

# 2. Excel with sheet name specified
df.to_excel('developers_named_sheet.xlsx',
            sheet_name='Developer_Data',
            index=False)
print("Excel with named sheet export completed: developers_named_sheet.xlsx")

Basic Excel export completed: developers_basic.xlsx
Excel with named sheet export completed: developers_named_sheet.xlsx